import { writable } from "svelte/store";
import { HDWebSocket, WebSocketState } from "../websockets";

export const state = writable(WebSocketState.Pending);
export const data = writable(null);

let overide = {
  data: {
    runs: 2,
    deaths: 0,
    wins: 1,
    kills: 38,
    score: 100000,
    time: 19265,
    run_state: {
      visit_mothership: true,
      visit_worm: true,
      died: false,
      won: true,
      kills: 454,
      score: 197725,
      time: 445551,
      areas: [
        {
          completed: true,
          time: 46150,
          time_pace: 46150,
          score: 5000,
          score_pace: 5000,
          levels: [
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 12033,
              time_fract: 930492,
              score: 0,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 11133,
              time_fract: 855789,
              score: 2000,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 12615,
              time_fract: 958068,
              score: 1500,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 10366,
              time_fract: 788848,
              score: 1500,
            },
            null,
            null,
          ],
        },
        {
          completed: true,
          time: 55500,
          time_pace: 101650,
          score: 3750,
          score_pace: 8750,
          levels: [
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 19384,
              time_fract: 511535,
              score: 0,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 13282,
              time_fract: 585357,
              score: 2500,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 8149,
              time_fract: 625839,
              score: 0,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 14683,
              time_fract: 299011,
              score: 1250,
            },
            null,
            null,
          ],
        },
        {
          completed: true,
          time: 148366,
          time_pace: 250016,
          score: 7800,
          score_pace: 16550,
          levels: [
            {
              completed: true,
              is_worm: true,
              is_mothership: false,
              time: 50216,
              time_fract: 292419,
              score: 1800,
            },
            {
              completed: true,
              is_worm: true,
              is_mothership: false,
              time: 62133,
              time_fract: 783828,
              score: 3750,
            },
            null,
            {
              completed: true,
              is_worm: false,
              is_mothership: true,
              time: 6949,
              time_fract: 705200,
              score: 0,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 20950,
              time_fract: 649963,
              score: 2250,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 8115,
              time_fract: 981277,
              score: 0,
            },
          ],
        },
        {
          completed: true,
          time: 118515,
          time_pace: 368532,
          score: 21175,
          score_pace: 37725,
          levels: [
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 42516,
              time_fract: 881958,
              score: 9625,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 10033,
              time_fract: 186351,
              score: 9625,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 14315,
              time_fract: 810455,
              score: 1750,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 51650,
              time_fract: 48645,
              score: 175,
            },
            null,
            null,
          ],
        },
        {
          completed: true,
          time: 77031,
          time_pace: 445564,
          score: 10000,
          score_pace: 47725,
          levels: [
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 18231,
              time_fract: 869796,
              score: 1000,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 15282,
              time_fract: 576263,
              score: 5000,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 16100,
              time_fract: 504646,
              score: 4000,
            },
            {
              completed: true,
              is_worm: false,
              is_mothership: false,
              time: 27416,
              time_fract: 983642,
              score: 0,
            },
            null,
            null,
          ],
        },
      ],
    },
  },
};

export const ws = new HDWebSocket("session", "Session", state, data);
